### PR TITLE
Implement XDG Base Directory specification

### LINKED ISSUE #400: `XDG_CONFIG_HOME` is not respected
The primary config file location is currently hardcoded as `~/.config/ia.ini`. Instead, it should use the `XDG_CONFIG_HOME` environment variable if set, defaulting to `${HOME}/.config` ([specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)).

I'll fix this together with #399 but wanted to file an issue anyway so it isn't forgotten.

### PR DESCRIPTION
**Pull request by JustAnotherArchivist**
`ia` will attempt the following paths in this order, using the first existing file:

- `${XDG_CONFIG_HOME}/internetarchive/ia.ini` (with `XDG_CONFIG_HOME` defaulting to `${HOME}/.config` if not set or invalid)
- `~/.config/ia.ini`
- `~/.ia`

When none of these paths exist on creating a config file (`ia configure`), the first one is used and directories are created as necessary.

Closes #400

### CODE REVIEW

**Comment by JustAnotherArchivist** [comment]
A note on `os.environ['HOME']` vs `os.expanduser('~')`: the XDG specification requires using `$HOME`. `os.expanduser` falls back to using the password database or the root directory if `$HOME` doesn't exist and is therefore not fit for purpose. In practice, this shouldn't matter as POSIX *requires* the presence of that environment variable, but I feel like it was worth mentioning anyway.

**Comment by JustAnotherArchivist** [comment]
For some reason, `$HOME` apparently isn't set in Travis CI. Lovely...
Not sure what the reason for that is. Smells like a bug on Travis's side.

I've successfully tested this code locally with a POSIX-compliant environment in all scenarios I could think of.

**Comment by JustAnotherArchivist** [comment]
Rethinking this, I suppose `ia` should also work on Windows, where `$HOME` doesn't exist as far as I know. Perhaps using `~` is better after all; on any properly POSIX-compliant system, it will still behave according to the specification since `expanduser` uses `$HOME` if set. @jjjake, any thoughts on this?

**Comment by JustAnotherArchivist** [comment]
I made that change from `$HOME` to `~` as I can't really think of a good reason not to do that. The specification doesn't say anything about what should happen if `$HOME` isn't present, presumably because it assumes a POSIX-compliant system (without mentioning it). And on such systems, the new code will still behave according to the specification because Python's expansion uses `$HOME` if present on Unix and only falls back to the password database if not; on Windows, `$HOME` is useless anyway.

I would still like to figure out why the build failed though. I wrote to Travis CI, and they confirmed that `$HOME` works correctly in an independent test build. I'll probably create a separate PR to play with that.

Also, I still want to add some tests here to ensure that a #399 situation can't happen again. So this isn't ready for merging yet.

**Comment by JustAnotherArchivist** [comment]
Tests are succeeding except on Python 2.7 because `tempfile.TemporaryDirectory` doesn't exist there. I could try to reimplement that, but Py2 is EOL and ia is already broken on it (#385), so I'm not sure that's worth the effort. @jjjake, please advise.

**Comment by JustAnotherArchivist** [comment]
I took a quick look at the implementation of `tempfile.TemporaryDirectory`, and it's more complex than I thought. If dropping Py2 support is not yet an option, skipping these tests on Py2 would be another possibility.

**Comment by JustAnotherArchivist** [comment]
Alright, I understand. To be clear, it's only the tests that are held back by this; the actual code should not be Py3-specific in any way.

I'll try to write a minimal crutch for Py2 that emulates the key part of `TemporaryDirectory`. I have no desire to reimplement its [complex error handling](https://github.com/python/cpython/blob/b4884083aed9bfec22c4da0e0223ad6a04a4bef2/Lib/tempfile.py#L766) though – a lot of things in that area changed between Py2 and Py3 and I haven't written code for Py2 in years... But it should be good enough to get the test suite running on CI at least.

**Comment by JustAnotherArchivist** [comment]
I realised today that `write_config_file` was broken on Python 2 for the same reason as the tests were previously (lack of `exist_ok` kwarg), but because there were no tests for that method at all, it didn't trip anything. I refactored that code slightly to decouple the IA login from the config file writing and added tests for all of that as well.

This should now be ready for review and merging. :-)

**Comment by jjjake** [comment]
Thanks again, @JustAnotherArchivist!

**Pull request merged**
