### PR TITLE
Switched to a TQDM bar that adapts for both chat & notebooks

### PR DESCRIPTION
**Pull request by LucaCappelletti94**

### CODE REVIEW

**Comment by cclauss** [comment]
As discussed at https://github.com/jjjake/internetarchive/pull/335#issuecomment-1046174861, I think a migration to https://pypi.org/project/rich-cli would offer many more possibilities for future expansion.

**Comment by LucaCappelletti94** [comment]
Yes, but that would not address the user experience when using Jupyter Notebooks, which is why I made this pull request.

**Review by cclauss — APPROVED** [review]

**Comment by cclauss** [comment]
Failing tests should be fixed by #571

**Comment by cclauss** [comment]
Please rebase to ensure that all tests pass.

**Comment by LucaCappelletti94** [comment]
Hi @cclauss, I haven't understood whether I should be doing anything. I am not familiar with the CI suite of this library.

**Comment by cclauss** [comment]
I fixed the CI in #571 which has now been merged into the current `master` branch.  All you need to do is `git rebase master` so this pull request is updated to use the changes in that new `master` branch.

**Comment by LucaCappelletti94** [comment]
Is this correct?

**Pull request closed without merging**
