### PR TITLE
host could be same as in get_auth_config

### PR DESCRIPTION
**Pull request by Harsh-br0**
Raises a weird invalid host error without default arg

### CODE REVIEW

**Comment by jimman2003** [comment]
https://github.com/internetarchive/openlibrary-client/issues/322 is caused by this..

**Review by jimman2003 — APPROVED** [review]
I think this will cover the default case quite well.. I tested this by setting the host argument when calling ia.configure , and that works

**Comment by jjjake** [comment]
Any thoughts/feedback on this @cclauss?

**Review by cclauss — APPROVED** [review]
Seems like the correct default to me.

**Pull request merged**
