### PR TITLE
Fixing tests

### PR DESCRIPTION
**Pull request by JesseWeinstein**
These tests fail (at least for me). These changes fix them. <s>There is still one failing test, `test_get_auth_config` which appears to be due to the test cookies not being accepted, which I haven't been able to figure out. :-( </s>

I have now worked around the bug(s) in the responses & requests packages such that ALL THE TESTS PASS.

### CODE REVIEW

**Comment by JesseWeinstein** [comment]
I wanted to put them in the function so the Ugly Hack(TM) is locallized, and can be more easily taken out once the underlying issue is fixed.

**Comment by JesseWeinstein** [comment]
It doesn't actually fix it. :-( Still figuring out what went wrong.

**Comment by JesseWeinstein** [comment]
OK, now the test_config.py tests work -- but `test_ia_metadata_formats` fails, because @jjjake added two files to `iacli-test-item60` with `JSON` and `HTML` formats, respectively.

See https://archive.org/history/iacli-test-item60

**Comment by jjjake** [comment]
@JesseWeinstein I've removed the JSON and HTML formats from `iacli-test-item60`.

**Pull request merged**
