### PR TITLE
URL attributes

### PR DESCRIPTION
**Pull request by JesseWeinstein**
OK, I think this may be the last (or nearly last) of my pile of changes.

### CODE REVIEW

**Comment by JesseWeinstein** [comment]
Ping.

**Comment by jjjake** [comment]
@JesseWeinstein tests are failing for this PR. Can you fix, and I'll take a look?

**Comment by JesseWeinstein** [comment]
Oops, I forgot to check if they were passing. Fixed now (I hope).

**Comment by jjjake** [comment]
@JesseWeinstein how helpful is the `attrs` library? I'd strongly prefer to limit dependencies (even light weight ones) where possible.

Everything else looks good, thanks!

**Comment by JesseWeinstein** [comment]
The `attrs` library is a lovely piece of work (and I'd be interested in making use of it more widely in the library, eventually) -- but it's pretty unnecessary here. I'm glad to switch back to the previous implementation if you'd prefer.

**Comment by jjjake** [comment]
Sorry I didn't get back to you earlier @JesseWeinstein. I still would like to limit the dependencies, and not add `attrs` (at least for now). I'm happy to merge if you're willing to remove `attrs`, otherwise I'll go ahead and close this PR. Thanks.

**Comment by JesseWeinstein** [comment]
Sure, I'll switch back to the previous implementation.

**Comment by JesseWeinstein** [comment]
OK, switched back, and the tests pass. Please merge when you get a chance!

**Comment by jjjake** [comment]
Thanks Jesse!

**Pull request merged**
