### PR TITLE
Add clue for folks running on thinly-configured systems

### PR DESCRIPTION
**Pull request by wumpus**

### CODE REVIEW

**Comment by saper** [comment]
Well, Linux distributions are not a whole world....

**Comment by wumpus** [comment]
Most Mac devs use ports, and the package names are similar. Windows, yeah, that's complicated.

**Comment by saper** [comment]
I mean also this that even not all Linux distributions have a concept of "-dev" packages.

**Comment by wumpus** [comment]
Uh, sure, there are an infinite number of Linux distros and some have different naming schemes. I think this short bit of advice works for the majority of devs... and at the least, it highlights the fact that there are dependencies to the OS which are not going to be automatically satisfied. Most python packages just work.

**Comment by wumpus** [comment]
Whoops, meant to make this 2nd thing a separate pull request.

**Pull request closed without merging**
